spring:
  application:
    name: Hello OIDC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-06128998.okta.com/oauth2/aus7unshngqfk7HA85d7
server:
  port: 8081
  error:
    include-stacktrace: ALWAYS

logging:
  level:
    root: info
    org.springframework.security: DEBUG
