spring:
  application:
    name: Hello OIDC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/pleiade
          jwk-set-uri: http://localhost:8083/auth/realms/pleiade/protocol/openid-connect/certs
server:
  port: 8081
  error:
    include-stacktrace: ALWAYS

logging:
  level:
    root: info
    org.springframework.security: DEBUG
